export const DISTRITOS_FISCALES = [
  { text: 'Amazonas', value: 'amazonas' },
  { text: 'Ancash', value: 'ancash' },
  { text: 'Apurimac', value: 'apurimac' },
  { text: 'Arequipa', value: 'arequipa' },
  { text: 'Ayacucho', value: 'ayacucho' },
  { text: 'Cajamarca', value: 'cajamarca' },
  { text: 'Callao', value: 'callao' },
  { text: 'Cañete', value: 'canete' },
  { text: 'Cusco', value: 'cusco' },
  { text: 'Huancavelica', value: 'huancavelica' },
  { text: 'Huánuco', value: 'huanuco' },
  { text: 'Huaura', value: 'huaura' },
  { text: 'Ica', value: 'ica' },
  { text: 'Junin', value: 'junin' },
  { text: 'La Libertad', value: 'la_libertad' },
  { text: 'Lambayeque', value: 'lambayeque' },
  { text: 'Lima', value: 'lima' },
  { text: 'Lima Este', value: 'lima_este' },
  { text: 'Lima Noroeste', value: 'lima_noroeste' },
  { text: 'Lima Norte', value: 'lima_norte' },
  { text: 'Lima Sur', value: 'lima_sur' },
  { text: 'Loreto', value: 'loreto' },
  { text: 'Madre de Dios', value: 'madre_de_dios' },
  { text: 'Moquegua', value: 'moquegua' },
  { text: 'Pasco', value: 'pasco' },
  { text: 'Piura', value: 'piura' },
  { text: 'Puno', value: 'puno' },
  { text: 'San Martin', value: 'san_martin' },
  { text: 'Santa', value: 'santa' },
  { text: 'Selva Central', value: 'selva_central' },
  { text: 'Sullana', value: 'sullana' },
  { text: 'Tacna', value: 'tacna' },
  { text: 'Tumbes', value: 'tumbes' },
  { text: 'Ucayali', value: 'ucayali' }
];

export default DISTRITOS_FISCALES;
